AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  Sample SAM Template for {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: {{ cookiecutter.runtime | tojson }}
    MemorySize: 1024
    CodeUri: .
    Environment:
      Variables:
        APP_ENV: prod
    Layers:
      - !Ref PhpLayer

Parameters:
  PhpLayer:
    Type: String
    Description: PHP layer ARN
    Default: arn:aws:lambda:{{ cookiecutter.aws_region }}:873528684822:layer:{{ bref_php_layer_name(cookiecutter.architectures.value, cookiecutter.php_version) }}:{{ bref_layer_version(cookiecutter._bref_layers, bref_php_layer_name(cookiecutter.architectures.value, cookiecutter.php_version), cookiecutter.aws_region) }}

Resources:
  WebFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: public/index.php
      Timeout: 28
      Environment:
        Variables:
          BREF_RUNTIME: 'Bref\FpmRuntime\Main'
      {%- if cookiecutter.architectures.value != [] %}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{ arch }}
      {%- endfor %}
      {%- endif %}
      Events:
        DefaultRoute:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
    Metadata:
      BuildMethod: makefile

  ConsoleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/console
      Timeout: 120
      Environment:
        Variables:
          BREF_RUNTIME: 'Bref\ConsoleRuntime\Main'
      {%- if cookiecutter.architectures.value != [] %}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{ arch }}
      {%- endfor %}
      {%- endif %}
    Metadata:
      BuildMethod: makefile

  WebLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${WebFunction}"

  ConsoleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ConsoleFunction}"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebFunctionArn:
    Description: Current Lambda function version
    Value: !GetAtt WebFunction.Arn
  ConsoleFunctionArn:
    Description: Current Lambda function version
    Value: !GetAtt ConsoleFunction.Arn
  HttpApiId:
    Description: Id of the HTTP API
    Value: !Ref HttpApi
  HttpApiUrl:
    Description: URL of the HTTP API
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}'
