AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  Sample SAM Template for {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  PhpLayer:
    Type: String
    Description: PHP layer ARN
    Default: arn:aws:lambda:{{ cookiecutter.aws_region }}:534081306603:layer:{{ bref_php_layer_name(cookiecutter.architectures.value, cookiecutter.php_version) }}:{{ bref_layer_version(cookiecutter._bref_layers, bref_php_layer_name(cookiecutter.architectures.value, cookiecutter.php_version), cookiecutter.aws_region) }}
  PhpFpmLayer:
    Type: String
    Description: PHP FPM layer ARN
    Default: arn:aws:lambda:{{ cookiecutter.aws_region }}:534081306603:layer:{{ bref_php_layer_name(cookiecutter.architectures.value, cookiecutter.php_version, 'fpm') }}:{{ bref_layer_version(cookiecutter._bref_layers, bref_php_layer_name(cookiecutter.architectures.value, cookiecutter.php_version, 'fpm'), cookiecutter.aws_region) }}
  ConsoleLayer:
    Type: String
    Description: Console layer ARN
    Default: arn:aws:lambda:{{ cookiecutter.aws_region }}:534081306603:layer:console:{{ cookiecutter._bref_layers['console'][cookiecutter.aws_region] }}

Resources:
  ConsoleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      CodeUri: .
      Handler: bin/console
      Runtime: {{ cookiecutter.runtime | tojson }}
      Layers:
        - !Ref PhpLayer
        - !Ref ConsoleLayer
      {%- if cookiecutter.architectures.value != [] %}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{ arch }}
      {%- endfor %}
      {%- endif %}
    Metadata:
      BuildMethod: makefile

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: public/index.php
      Runtime: {{ cookiecutter.runtime | tojson }}
      Layers:
        - !Ref PhpFpmLayer
      {%- if cookiecutter.architectures.value != [] %}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{ arch }}
      {%- endfor %}
      {%- endif %}
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
